### ISSUE TITLE
Trying to save the model

### ISSUE THREAD

**Issue by rizwanishaq** [lshug/first-order-model-tf#15]
Hi, 
I am trying to use first-order-model-tf for saving model in saved_model, but I am getting following error, using tensorfllow 2.5.0
```
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
Traceback (most recent call last):
  File "/content/first-order-model-tf/build.py", line 99, in <module>
    build(checkpoint_path, config_path, output_name, parser.module, parser.predictiononly, parser.hardcode, parser.tfjs, parser.staticbatchsize, parser.nolite, parser.float16)
  File "/content/first-order-model-tf/build.py", line 50, in build
    generator = build_generator(checkpoint_path, not prediction_only, **config["dataset_params"], **config["model_params"]["generator_params"], **config["model_params"]["common_params"], single_jacobian_map=single_jacobian_map, static_batch_size=static_batch_size)
  File "/content/first-order-model-tf/firstordermodel.py", line 1059, in build_generator
    return Generator(checkpoint=checkpoint, full_output=full_output, static_batch_size=static_batch_size, **kwargs)
  File "/content/first-order-model-tf/firstordermodel.py", line 1033, in __init__
    static_batch_size=static_batch_size,
  File "/content/first-order-model-tf/firstordermodel.py", line 973, in build_generator_base
    model = keras.Model(inputs, out_dict)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/tracking/base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py", line 115, in __init__
    self._init_graph_network(inputs, outputs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/tracking/base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py", line 152, in _init_graph_network
    self._validate_graph_inputs_and_outputs()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py", line 729, in _validate_graph_inputs_and_outputs
    '(thus holding past layer metadata). Found: ' + str(x))
ValueError: Output tensors of a Functional model must be the output of a TensorFlow `Layer` (thus holding past layer metadata). Found: <tensorflow.python.keras.layers.core.Lambda object at 0x7f3ea93664d0>
```

**Comment by lshug** [comment]
Whoops, I accidentally deleted the deformed_source-reshaping layer's input after converting it from reshape to lambda reshape a few commits ago. I was testing with --predictiononly builds so the error slipped in. I pushed a fix. Can you retry?

**Comment by rizwanishaq** [comment]
@lshug It is working, now, one more thing, about generator saved_model, when I check saved_model_cli, it shows me like, that

```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['kp_driving'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10, 2)
        name: serving_default_kp_driving:0
    inputs['kp_driving_jacobian'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10, 2, 2)
        name: serving_default_kp_driving_jacobian:0
    inputs['kp_source'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 10, 2)
        name: serving_default_kp_source:0
    inputs['kp_source_jacobian'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 10, 2, 2)
        name: serving_default_kp_source_jacobian:0
    inputs['source_image'] tensor_info:
        dtype: DT_FLOAT
        shape: (1, 256, 256, 3)
        name: serving_default_source_image:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['prediction'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 256, 256, 3)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict
```

isn't source_image, should be (-1,256,256,3), and kp_source as (-1, 10,2,2), and kp_source_jacobian as (-1, 10,2,2)??? as for serving it should be like that??? is it possible??

**Comment by lshug** [comment]
Thanks for opening the issue. Now that it's resolved I'm closing it.

As for your other question, -1 in tensor shape indicates that the dimension is dynamic. Usually dynamic shapes are used for batch sizes, so that a single constructed graph will be able to handle inputs with different batch sizes. In case of generator's source image, kp_source, and  kp_source_jacobian inputs, they are always provided as a size-1 batch, because regardless of how many frames you are processing in a single pass (i.e. the batch size of kp_drivin/kp_driving_jacobian), you always use the same source image and source image kps/jacobians. Since they never change, there's no need to give them a dynamic shape.

**Comment by rizwanishaq** [comment]
@lshug Thanks.
That's batching... basically, I am running everything in real-time, and there are multiple batches can come to tensorflow-serving, i.e. 2 streams at the same time, for different source image, so that we can process all the batches at the same time. I will try by setting that to -1, and let you know about possible errors.

**Comment by lshug** [comment]
That won't work. Basically, the models treat "one batch" as one batch of frames from the same driving video, rather than treating one batch as a collection of pairs of source images and driving videos. Pushing even one full driving video through the models all at once will likely exhaust most if not all of the available vram (you can simulate what that would look like by running animation task with batch size equal to the number of frames in the video). Attempting this with multiple input pairs definitely would, even if it was possible with the current architecture.
