### ISSUE TITLE
Distorted output for 512x512 model even with --loadwithtorch

### ISSUE THREAD

**Issue by RaghavaDhanya** [lshug/first-order-model-tf#17]
Hi,
I tried to run 512 model that's based of https://github.com/adeptflax/motion-models . It works fine on the original pytorch version but on tf it has distorted output.
![output](https://user-images.githubusercontent.com/13164365/122750111-c158e080-d2ab-11eb-9f26-bfe39101d38e.gif)

Here is a colab to reproduce the issue: https://colab.research.google.com/drive/1DQURIyffaOQvVKsRFQA-zSKYKbVYpzvu?usp=sharing

Any ideas on what could be breaking?

**Comment by lshug** [comment]
Hello. Thanks for the issue, great catch. I hadn't actually tested the model with higher resolutions. 

Looking at the intermediate outputs, it looks like things are identical between tf on torch right up until the the deformation generated by the dense motion module gets upsampled to match the spatial resolution of the downblock-generated features. When the frame shape is 256x256 that step doesn't need to happen, since both the outputs of downblock and the deformation would have 64x64 spatial shape. But when the resolution is 512x512, downblock output is 128x128, so deformation needs to get upsampled. Looks like there's an error in my keras layer implementation of torch's 2d bilinear upsampling kernel (BilinearInterpolate). I'll try to fix and get back to you.

**Comment by lshug** [comment]
The issue was a small typo that assigned the value of h0 to w0. All fixed now. It won't need --loadwithtorch or manual adjustment of sigma either.

https://user-images.githubusercontent.com/73127106/122990389-f1d87180-d3b4-11eb-8225-44a2e610b9eb.mp4
