### ISSUE TITLE
Removed 'tf.autograph.experimental.do_not_convert'

### ISSUE THREAD

**Issue by norris9410** [lshug/first-order-model-tf#19]
Hi, thanks again for updating the converting scripts. 

I notice that in the previous version, there are many functions decorated with @tf.autograph.experimental.do_not_convert. For example, 
![1](https://user-images.githubusercontent.com/32683143/127992786-d0fad8c1-2bc9-4eba-a698-28fc1844da02.PNG)
![2](https://user-images.githubusercontent.com/32683143/127992820-126c97b9-88e4-4c5c-9da0-b10d4ad26b14.PNG)

Could you explain a little bit the purpose of using 'tf.autograph.experimental.do_not_convert' before?
 And why not using it in this newest repo?

**Comment by lshug** [comment]
Hello. Sorry for the late response. I haven't had much time to attend to this repo in the past few weeks. 

The reason for disabling autograph tracing on some functions in older commits with ```do_not_convert``` was a [bug in early TF2.5 release candidates](https://github.com/tensorflow/tensorflow/issues/48289) on Python 3.9 that made autograph unable to convert functions that contained tensor slicing with colons, due to using astunparse, which did not support this syntax. At the time the repo had a dependency on the release candidate because of the use of tf lite signature runner, which wasn't available in TF2.4. Since 2.5rc3, autograph uses python's built-in ast module to do unparsing, which supports that syntax, so disabling tracing with do_not_convert is no longer necessary.  Hope that answers your question.
