### ISSUE TITLE
General Questions about running....

### ISSUE THREAD

**Issue by ElmiraNa** [lshug/first-order-model-tf#20]
Hi @lshug 
I appreciate your effort in advance.
I ran first-order-model first, but it is  memory over consuming and is not optimized in term of time consuming too.
What about your project?
the other question is if what does happen when we execute build.py. should we run it every time for any driving video and source image or just for the first time?

**Comment by lshug** [comment]
Hello,

Concerning memory usage, the two repos should be fairly comparable when using this one at batch size 1. I definitely wouldn't say either mine or the original are "overconsuming" in terms of memory. Assuming backprop is disabled, intermediate outputs are not saved except when needed for later stages, and spatial resolution is 256x256, the overall memory usage of the tensors necessary for inference runs (weights for kp_detector and generator) is exactly 239260316 bytes/240MB. 

The big memory sink for both implementations is the loading of the driving videos frames into the memory before inference. At 256x256, each second of the driving video is 18874368 bytes/18MB. This still shouldn't be a problem for usual sizes of several seconds, but it does mean that each minute in a driving video will require around one GB of memory. A way to avoid this is to write a custom loader that reads the driving video from disk into memory frame batch by frame batch instead of all at once. 

As for speed, assuming GPU use, this repo does outperform the original at higher batch sizes. When batch size is set to 16 it can be more than twice as fast. That said, the higher the batch size, the more memory the intermediate outputs will take. I have a [benchmarking colab set up that compares the two,](https://colab.research.google.com/drive/1CHlfG792RifIpwYQqqUNHGS_3rUe16vQ?usp=sharing), which can also be used to generate tensorboard profiler files, which you can use to inspect memory use in detail. 
 
As for build.py, running it is only necessary for generating SavedModels and TF Lite files and only has to be done once. If you just want to run the model, you can use run.py without building those first. 

Please feel free to ask any other questions.
